### ISSUE TITLE
Environment Level Policy is getting applied incorrectly at the project level

### ISSUE THREAD

**Issue by codejnki** [plexsystems/nifi-cluster-coordinator#26]
Scenario:

```
project-a
|--environment-a
|--environment-b
```

Policy configuration

```
- name: 'modify the component'
  component_type: environment
  component_name: 'project-a:envrionment-a'
  user_group:
    - some-team
```

Expected Behavior:
Members of `some-team` have modify permissions on `project-a:environment-a` but **no** modify permissions on `project-a:environment-b`

Actual Behavior:
Members of `some-team` have modify permissions on **both** environments.

Root Cause:
The `modify the component` permission is being applied at the `project-a` process group and the other environments are inheriting this policy.
